### ISSUE TITLE
Connecting a LiPo battery to Waveshare e-Paper ESP32 board

### ISSUE THREAD

**Issue by knyar** [maxbbraun/accent#21]
Hi @maxbbraun, thanks a lot for sharing the details about this project. I have a hardware-related question, I hope it's OK to ask it here.

In your [medium post](https://onezero.medium.com/meet-accent-352cfa95813a) you mentined that you connected the board to a 3.7v LiPo battery. I noticed that the board only has 5v and 3.3v pins, while LiPo batteries produce 4.2v while fully charged.

Did you use a voltage regulator while connecting the battery to the 3.3v pin, or does the board work fine with the battery connected directly to the 3.3v (or 5v)? Thanks!

**Comment by maxbbraun** [comment]
I directly connected it to the 3.3V pin. Not the cleanest solution, but it worked.

**Comment by knyar** [comment]
Thanks! I will try connecting directly as well.
