### ISSUE TITLE
Internal Server Error on /hello/<USER_KEY>

### ISSUE THREAD

**Issue by bdaneshgar** [maxbbraun/accent#40]
I am thinking out loud. I get a server error when testing  `/hello/<USER_KEY>` 

My calendar is probably set up incorrectly: 
- I have only filled `oath_client/google_calendar `document with the `client_id` and `client_secret`
- I have not filled out the `/users/<USER_KEY>/google_calendar_credentials`
- Is `/users/<USER_KEY>/google_calendar_credentials` to be set up in the `/hello/<USER_KEY>` page.

Any insight into helping me get into thepage is much appreciated! 

> [/hello/<USER_KEY>](http://localhost:8080/hello/%3CUSER_KEY%3E) for the settings UI to edit user-specific data.

Internal Server Error

> [/next?key=<USER_KEY>](http://localhost:8080/next?key=%3CUSER_KEY%3E) for the time in milliseconds until the next schedule entry.

This works

> [/epd?key=<USER_KEY>](http://localhost:8080/epd?key=%3CUSER_KEY%3E) for the currently scheduled client image used by the e-paper display.

This downloads serial gibberish 

> [/gif?key=<USER_KEY>](http://localhost:8080/gif?key=%3CUSER_KEY%3E) for a GIF version of the currently scheduled image for testing.

this triggers the `settings_response` function in `response.py`

> [/artwork?key=<USER_KEY>](http://localhost:8080/artwork?key=%3CUSER_KEY%3E) to bypass the schedule and get the artwork image directly.

This works

> [/city?key=<USER_KEY>](http://localhost:8080/city?key=%3CUSER_KEY%3E) to bypass the schedule and get the city image directly.

This works

> [/commute?key=<USER_KEY>](http://localhost:8080/commute?key=%3CUSER_KEY%3E) to bypass the schedule and get the commute image directly.

This works

> [/calendar?key=<USER_KEY>](http://localhost:8080/calendar?key=%3CUSER_KEY%3E) to bypass the schedule and get the calendar image directly.

Internal Server Error

> [/everyone?key=<USER_KEY>](http://localhost:8080/everyone?key=%3CUSER_KEY%3E) to bypass the schedule and get the everyone image directly.

I am everyone

> [/wittgenstein?key=<USER_KEY>](http://localhost:8080/wittgenstein?key=%3CUSER_KEY%3E) to bypass the schedule and get the wittgenstein image directly.

This works.

**Comment by bdaneshgar** [comment]
I did notice that my browser autocorrected to `oath_clients`. I noticed in the `README.md`, there is a reference to both `oauth_client` and `oauth_clients` and I see that only `oauth_clients` is valid.

I am still having trouble with my `/calendar?key=<USER_KEY>` and `/hello/<USER_KEY>`

**Comment by bdaneshgar** [comment]
I took out extraneous URIs from my OAuth Client and it now works!

**Comment by maxbbraun** [comment]
Thanks for catching the typo!
